Repository JacksonBurns/astartes, pull requests merged in 2023-02, with the labels that each got.

#39 only run pr coverage check on ready to review PRs
  .github/workflows/coverage_reject.yml
  .github/workflows/run_tests.yml
Labels: PR Ready for Review

#41 switch to pyproject.toml
  .github/workflows/check_pypi_build.yml
  .github/workflows/coverage_reject.yml
  .github/workflows/format_code.yml
  .github/workflows/run_tests.yml
  .github/workflows/update_jors_branch.yml
  MANIFEST.in
  README.md
  pyproject.toml
  requirements.txt
  setup.py
Labels: enhancement, PR Ready for Review

#42 Interface sampler refactor
  .github/workflows/format_code.yml
  README.md
  astartes/__init__.py
  astartes/astartes.py
  astartes/interfaces/__init__.py
  astartes/interfaces/train_test_split_images.py
  astartes/main.py
  astartes/molecules.py
  astartes/samplers/__init__.py
  astartes/samplers/abstract_sampler.py
  astartes/samplers/dbscan.py
  astartes/samplers/doptimal.py
  astartes/samplers/duplex.py
  astartes/samplers/extrapolation/__init__.py
  astartes/samplers/extrapolation/kmeans.py
  astartes/samplers/extrapolation/scaffold.py
  astartes/samplers/interpolation/__init__.py
  astartes/samplers/interpolation/dbscan.py
  astartes/samplers/interpolation/doptimal.py
  astartes/samplers/interpolation/duplex.py
  astartes/samplers/interpolation/kennardstone.py
  astartes/samplers/interpolation/mtsd.py
  astartes/samplers/interpolation/optisim.py
  astartes/samplers/interpolation/random_split.py
  astartes/samplers/interpolation/sphere_exclusion.py
  astartes/samplers/mtsd.py
  astartes/samplers/optisim.py
  astartes/samplers/random_split.py
  astartes/samplers/sampler.py
  astartes/samplers/sphere_exclusion.py
  astartes/utils/__init__.py
  astartes/utils/blank.py
  astartes/utils/exceptions.py
  astartes/utils/warnings.py
  pyproject.toml
  test/interfaces/__init__.py
  test/interfaces/test_images_interface.py
  test/interfaces/test_molecules_interface.py
  test/samplers/test_DBSCAN.py
  test/samplers/test_DUPLEX.py
  test/samplers/test_MTSD.py
  test/samplers/test_Scaffold.py
  test/samplers/test_doptimal.py
  test/samplers/test_kennard_stone.py
  test/samplers/test_kmeans.py
  test/samplers/test_optisim.py
  test/samplers/test_sphere_exclusion.py
  test/test_astartes.py
  test/test_molecules.py
  test/utils/test_exceptions.py
  test/utils/test_matrix_ops.py
Labels: PR Ready for Review

#47 Updated Implementation and Unit Testing for Kennard-Stone Sampler
  astartes/samplers/__init__.py
  astartes/samplers/interpolation/kennardstone.py
  test/samplers/test_kennard_stone.py
Labels: enhancement, PR Ready for Review

#51 Run `isort` as a CI Check
  .github/workflows/format_code.yml
  astartes/main.py
  astartes/samplers/__init__.py
  astartes/samplers/extrapolation/__init__.py
  astartes/samplers/extrapolation/kmeans.py
  astartes/samplers/interpolation/kennardstone.py
  astartes/samplers/interpolation/random_split.py
  docs/conf.py
  pyproject.toml
  test/samplers/test_kennard_stone.py
  test/samplers/test_kmeans.py
  test/test_astartes.py
  test/test_molecules.py
  test/utils/test_exceptions.py
Labels: enhancement, PR Ready for Review

#50 Revert back to sklearn train_test split for random splitting
  astartes/samplers/interpolation/random_split.py
  test/test_astartes.py
Labels: PR Ready for Review

#48 move sphere_exclusion, add fxn/test headers and imports
  README.md
  astartes/main.py
  astartes/samplers/__init__.py
  astartes/samplers/abstract_sampler.py
  astartes/samplers/extrapolation/__init__.py
  astartes/samplers/extrapolation/kmeans.py
  astartes/samplers/extrapolation/sphere_exclusion.py
  astartes/samplers/interpolation/__init__.py
  astartes/samplers/interpolation/sphere_exclusion.py
  docs/conf.py
  pyproject.toml
  test/samplers/test_sphere_exclusion.py
  test/test_astartes.py
  test/test_molecules.py
  test/utils/test_exceptions.py
Labels: enhancement, PR Ready for Review

#53 Add SamplerFactory to simplify train_test_split
  astartes/main.py
  astartes/utils/sampler_factory.py
Labels: PR Ready for Review

#55 add test for random and sampler factory
  .github/workflows/run_tests.yml
  astartes/molecules.py
  astartes/utils/exceptions.py
  test/samplers/test_random.py
  test/utils/__init__.py
  test/utils/test_exceptions.py
  test/utils/test_sampler_factory.py
Labels: PR Ready for Review

#56 Switch 'backend' to `train_val_test_split` instead of `train_test_split`
  astartes/__init__.py
  astartes/main.py
  astartes/molecules.py
  astartes/utils/exceptions.py
  astartes/utils/warnings.py
  test/samplers/test_kennard_stone.py
  test/samplers/test_random.py
  test/samplers/test_sphere_exclusion.py
  test/test_astartes.py
  test/test_molecules.py
Labels: enhancement, PR Ready for Review

#61 add transition to astartes docs page
  .github/workflows/gen_docs.yml
  docs/index.rst
  sklearn_to_astartes.md
Labels: documentation, PR Ready for Review

#62 Addition of Missing (and Improvement of Existing) Docstrings
  .github/workflows/run_tests.yml
  astartes/__init__.py
  astartes/main.py
  astartes/molecules.py
  astartes/samplers/abstract_sampler.py
  astartes/samplers/extrapolation/sphere_exclusion.py
  astartes/samplers/interpolation/random_split.py
  astartes/utils/sampler_factory.py
  test/samplers/test_DBSCAN.py
  test/samplers/test_DUPLEX.py
  test/samplers/test_MTSD.py
  test/samplers/test_Scaffold.py
  test/samplers/test_doptimal.py
  test/samplers/test_kmeans.py
  test/samplers/test_optisim.py
  test/samplers/test_sphere_exclusion.py
  test/test_astartes.py
  test/test_molecules.py
  test/utils/test_exceptions.py
Labels: PR Ready for Review
