Repository JacksonBurns/astartes, pull requests merged in 2023-06, with the labels that each got.

#121 Fix typo in RDB7 notebook
  examples/barrier_prediction_with_RDB7/RDB7_barrier_prediction_example.ipynb
Labels: PR Ready for Review

#124 add support for X, y, and labels of type other than np.ndarray
  README.md
  astartes/main.py
  astartes/utils/convert_to_array.py
  astartes/utils/exceptions.py
  astartes/utils/warnings.py
  pyproject.toml
  test/unit/utils/test_convert_to_array.py
Labels: bug, PR Ready for Review

#126 Improve Performance of Kennard-Stone, SPXY Samplers
  astartes/samplers/interpolation/kennardstone.py
  astartes/samplers/interpolation/spxy.py
Labels: enhancement, PR Ready for Review

#127 Support for Pandas Dataframe and Series
  README.md
  astartes/main.py
  astartes/utils/array_type_helpers.py
  astartes/utils/convert_to_array.py
  pyproject.toml
  test/unit/utils/test_convert_to_array.py
Labels: enhancement, PR Ready for Review

#132 add a `conda` package
  .github/workflows/publish_packages.yml
  .github/workflows/publish_to_pypi.yml
  README.md
Labels: enhancement, PR Ready for Review

#133 Add conda to the paper abstract
  paper.md
Labels: PR Ready for Review

#122 Add function to obtain values for a table
  README.md
  astartes/utils/exceptions.py
  astartes/utils/utils.py
  test/unit/utils/test_utils.py
Labels: PR Ready for Review
