Repository JacksonBurns/astartes, pull requests merged in 2023-03, with the labels that each got.

#64 Avoid redefining Python's native `NotImplementedError`
  astartes/utils/exceptions.py
  astartes/utils/sampler_factory.py
  test/test_astartes.py
Labels: PR Ready for Review

#71 Add SPXY Sampler, Fix Bug in Interpolative Sampler Set Filling
  astartes/main.py
  astartes/molecules.py
  astartes/samplers/__init__.py
  astartes/samplers/interpolation/__init__.py
  astartes/samplers/interpolation/spxy.py
  astartes/utils/sampler_factory.py
  test/samplers/test_kennard_stone.py
  test/samplers/test_random.py
  test/samplers/test_spxy.py
  test/test_astartes.py
  test/utils/test_sampler_factory.py
Labels: PR Ready for Review

#65 Scaffold splits
  README.md
  astartes/samplers/__init__.py
  astartes/samplers/extrapolation/scaffold.py
  astartes/utils/sampler_factory.py
  astartes/utils/warnings.py
  test/samplers/test_DBSCAN.py
  test/samplers/test_Scaffold.py
  test/test_molecules.py
  test/utils/test_exceptions.py
  test/utils/test_sampler_factory.py
Labels: PR Ready for Review

#66 README Update, PR and Issue Templates, Developer Instructions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
  README.md
  pyproject.toml
Labels: documentation, PR Ready for Review

#72 Add Actions Concurrency
  .github/workflows/coverage_reject.yml
  .github/workflows/run_tests.yml
Labels: PR Ready for Review

#74 Allow users to access the power hyperparameter for DBSCAN
  astartes/samplers/extrapolation/dbscan.py
Labels: enhancement, PR Ready for Review

#73 Improve scaffold
  astartes/samplers/extrapolation/scaffold.py
  test/samplers/test_Scaffold.py
Labels: enhancement, PR Ready for Review

#75 Allow arguments for KMeans to be accessible to users
  astartes/samplers/extrapolation/kmeans.py
Labels: enhancement, PR Ready for Review

#43 Add example notebook with Sci Dataset example
  examples/RDB7_barrier_prediction_example.ipynb
  examples/ccsdtf12_dz.csv
Labels: PR Ready for Review

#67 Examples: new notebook to demonstrate train_val_test_split and CI for notebooks
  .github/workflows/ipynb_ci.yml
  README.md
  examples/astartes_example.ipynb
  examples/train_val_test_split_example.ipynb
  postBuild
Labels: PR Ready for Review

#89 Set random seed
  README.md
  astartes/main.py
  astartes/molecules.py
  examples/RDB7_barrier_prediction_example.ipynb
  examples/train_val_test_split_example.ipynb
  sklearn_to_astartes.md
  test/samplers/test_kmeans.py
  test/samplers/test_optisim.py
  test/samplers/test_random.py
  test/samplers/test_sphere_exclusion.py
  test/test_astartes.py
  test/test_molecules.py
Labels: enhancement, PR Ready for Review

#90 Update description
  sklearn_to_astartes.md
Labels: documentation, PR Ready for Review

#93 Change behavior of `return_indices`
  astartes/main.py
  astartes/molecules.py
  examples/RDB7_barrier_prediction_example.ipynb
  sklearn_to_astartes.md
  test/test_astartes.py
Labels: PR Ready for Review

#95 Repo meta fixes
  .github/workflows/check_pypi_build.yml
  .github/workflows/format_code.yml
  .github/workflows/update_joss_branch.yml
  .gitignore
  LICENSE
  README.md
  sklearn_to_astartes.md
Labels: PR Ready for Review

#97 `astartes` v1.0 Release Candidate 1
  README.md
  pyproject.toml
Labels: PR Ready for Review

#100 Paper edits
  paper.bib
  paper.md
Labels: PR Ready for Review
